### ISSUE TITLE
可以同步获取用户信息吗，比如地区/年龄/性别

### ISSUE THREAD

**Issue by lovesnacks** [HEUDavid/WeiboSpider#1]
首先感谢大佬！！找了很多代码都有各种问题，这个真的超好用！！！
其次想问一下，能否在爬取微博数据的同时把发博人的信息一起爬下来呢？
或者只爬下来user_id,然后再用其他爬取用户信息的代码通过user_id匹配。
最后一个小问题是“时间格式异常”的原因是什么呀，我看了一下数据里面时间那一列没问题，这个应该不影响吧
![image](https://user-images.githubusercontent.com/41772072/57072690-22f71300-6d11-11e9-9c09-5562f20fdf20.png)

**Comment by HEUDavid** [comment]
哈哈哈， 真的有人用啊，我去==，get_datetime(self, s)格式化时间函数抛出异常了，的确不影响使用，我爬的时候没考虑19年以前的数据，所以像这样的格式的时间没有处理。

爬取发博人的详细数据也可以呀，目前爬取的博主主页，地址里的数字部分就是用户的id，可以用这id拿过来单独爬这个用户的数据，地区、年龄、性别等等用户属性。我还有个想法爬这个用户的所有微博来为其打标签。

目前实现的的基于关键字的爬虫，可以控制爬某个地区的微博。

额，这是我毕业设计的一部分内容，后面是做文本分析的内容了，还剩的爬虫部分只能后面有时间在写了。

**Comment by lovesnacks** [comment]
哈哈对啊！！超好用！！来自一个不会写代码却被老师要求爬微博的小渣渣~~再次感谢
我再去找找爬用户的代码吧~~~文本分析有代码吗嘿嘿嘿，方便的话可以上传吗？
祝你毕业顺利啦！！

**Comment by HEUDavid** [comment]
加我微信lorddw 交流 :) 我教你如何爬用户的所有微博 方便的话把文本分析代码给我分享一哈
